[#] Adds and runs linters
singnet/das-toolbox pull request #110
Opened 2024-08-23 19:31 UTC by Pedrobc89

- **add linters configuration files**
- **virtual environment to gitignore**
- **black formatter**
- **isort fix**
- **flake8 fixes**
- **add **all** to init files with imports**

Adds and runs linters in the project.
MyPy fix will be left to a future work.

2024-08-28 17:37 UTC, levisingularity approved these changes

2024-08-28 18:03 UTC, levisingularity requested changes
@Pedrobc89

2024-08-28 18:41 UTC, Pedrobc89 commented on src/pyproject.toml
> +[tool.isort]
[25c1d93](https://github.com/singnet/das-toolbox/pull/110/commits/25c1d9324558156f5cbf6c89aca5d4ee35bcfaed)
[0e64d73](https://github.com/singnet/das-toolbox/pull/110/commits/0e64d73ae4260a28eba73fdfc66c83cfb2273eec)

2024-08-29 17:15 UTC, andre-senna approved these changes

2024-08-29 17:32 UTC, merged